### ISSUE TITLE
server 502 error 

### ISSUE THREAD

**Issue by luiguangguan** [szabodanika/microbin#126]
A 502 error occurs when too many characters are entered. 
I use Nginx as a reverse proxy.
![image](https://user-images.githubusercontent.com/20753694/205490075-c1498b91-eaa2-47bd-8f75-b91b75b6fcd1.png)

==========    LOG      =======================
=
2022-12-04T15:49:57 [INFO] - MicroBin starting on http://0.0.0.0:8080
2022-12-04T15:49:57 [INFO] - Starting 1 workers
2022-12-04T15:49:57 [INFO] - Actix runtime found; starting in Actix runtime
2022-12-04T15:49:57 [INFO] - 172.19.0.1 "GET /pasta/falcon-mole-wasp HTTP/1.1" 200 728 "https://past.cent.xxxxxx.xyz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000519
2022-12-04T15:49:57 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pasta/falcon-mole-wasp" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000100
2022-12-04T15:49:57 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "https://past.cent.xxxxxx.xyz/pasta/falcon-mole-wasp" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000060
2022-12-04T15:50:07 [INFO] - 172.19.0.1 "GET /pastalist HTTP/1.1" 200 2698 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000376
2022-12-04T15:50:07 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000069
2022-12-04T15:50:10 [INFO] - 172.19.0.1 "GET /pasta/b67WOd HTTP/1.1" 200 3466 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.003249
2022-12-04T15:50:10 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pasta/b67WOd" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000060
2022-12-04T15:50:12 [INFO] - 172.19.0.1 "GET /remove/b67WOd HTTP/1.1" 302 0 "https://past.cent.xxxxxx.xyz/pasta/b67WOd" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000051
2022-12-04T15:50:12 [INFO] - 172.19.0.1 "GET /pastalist HTTP/1.1" 200 1175 "https://past.cent.xxxxxx.xyz/pasta/b67WOd" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000199
2022-12-04T15:50:12 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000061
2022-12-04T15:50:14 [INFO] - 172.19.0.1 "GET / HTTP/1.1" 200 6137 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000061
2022-12-04T15:50:14 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000068
2022-12-04T15:50:25 [INFO] - 172.19.0.1 "POST /upload HTTP/1.1" 302 0 "https://past.cent.xxxxxx.xyz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000274
2022-12-04T15:50:25 [INFO] - 172.19.0.1 "GET /pasta/bDPEKb HTTP/1.1" 200 4356 "https://past.cent.xxxxxx.xyz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.002891
2022-12-04T15:50:25 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pasta/bDPEKb" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000058
2022-12-04T15:51:38 [INFO] - 172.19.0.1 "GET /remove/bDPEKb HTTP/1.1" 302 0 "https://past.cent.xxxxxx.xyz/pasta/bDPEKb" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000052
2022-12-04T15:51:38 [INFO] - 172.19.0.1 "GET /pastalist HTTP/1.1" 200 1175 "https://past.cent.xxxxxx.xyz/pasta/bDPEKb" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000206
2022-12-04T15:51:38 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000057
2022-12-04T15:51:41 [INFO] - 172.19.0.1 "GET /pastalist HTTP/1.1" 200 1175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000309
2022-12-04T15:51:41 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000058
2022-12-04T15:51:41 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000050
2022-12-04T15:53:43 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000060
2022-12-04T16:00:13 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000059
2022-12-04T16:12:29 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pasta/bYDVOa" "Mozilla/5.0 (Linux; Android 12; SM-G9810) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36" 0.000074
2022-12-04T16:12:35 [INFO] - 172.19.0.1 "GET /pasta/bYDVOa HTTP/1.1" 200 728 "-" "Mozilla/5.0 (Linux; Android 12; SM-G9810) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36" 0.000210
2022-12-04T16:12:35 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pasta/bYDVOa" "Mozilla/5.0 (Linux; Android 12; SM-G9810) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36" 0.000055
2022-12-04T16:12:35 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "https://past.cent.xxxxxx.xyz/pasta/bYDVOa" "Mozilla/5.0 (Linux; Android 12; SM-G9810) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36" 0.000049
2022-12-04T16:44:08 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000062
2022-12-04T16:47:07 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000055
2022-12-04T16:50:16 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000050
2022-12-04T16:56:16 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000059
2022-12-04T17:09:35 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000134
2022-12-04T17:10:16 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000050
2022-12-04T17:17:22 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000059
2022-12-04T17:55:07 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000134
2022-12-04T17:56:59 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000050
2022-12-04T17:59:03 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000051
2022-12-04T18:22:07 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000138
2022-12-04T18:22:10 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000051
2022-12-04T18:25:14 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000057
2022-12-04T19:03:09 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000133
2022-12-04T19:03:22 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000054
2022-12-04T19:03:35 [INFO] - 172.19.0.1 "GET /pastalist HTTP/1.1" 200 1175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000212
2022-12-04T19:03:35 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000058
2022-12-04T19:06:28 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000051
2022-12-04T19:09:20 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000051
2022-12-04T19:11:06 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000052
2022-12-04T19:12:33 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000050
2022-12-04T19:34:03 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000060
2022-12-04T19:40:14 [INFO] - SIGTERM received; starting graceful shutdown
2022-12-04T19:40:14 [INFO] - Accept thread stopped
2022-12-04T19:40:14 [INFO] - Shutting down idle worker
2022-12-04T19:59:07 [INFO] - MicroBin starting on http://0.0.0.0:8080
2022-12-04T19:59:07 [INFO] - Starting 1 workers
2022-12-04T19:59:07 [INFO] - Actix runtime found; starting in Actix runtime
2022-12-04T19:59:50 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000181
2022-12-04T20:07:29 [INFO] - SIGTERM received; starting graceful shutdown
2022-12-04T20:07:29 [INFO] - Accept thread stopped
2022-12-04T20:07:29 [INFO] - Shutting down idle worker
2022-12-04T20:11:21 [INFO] - MicroBin starting on http://0.0.0.0:8080
2022-12-04T20:11:22 [INFO] - Starting 1 workers
2022-12-04T20:11:22 [INFO] - Actix runtime found; starting in Actix runtime
2022-12-04T20:12:14 [INFO] - SIGTERM received; starting graceful shutdown
2022-12-04T20:12:14 [INFO] - Accept thread stopped
2022-12-04T20:12:14 [INFO] - Shutting down idle worker
2022-12-04T20:13:44 [INFO] - MicroBin starting on http://0.0.0.0:8080
2022-12-04T20:13:44 [INFO] - Starting 1 workers
2022-12-04T20:13:44 [INFO] - Actix runtime found; starting in Actix runtime
2022-12-04T20:20:25 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000284
2022-12-04T20:20:26 [INFO] - 172.19.0.1 "GET /pastalist HTTP/1.1" 200 1175 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000418
2022-12-04T20:20:26 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000204
2022-12-04T20:20:28 [INFO] - 172.19.0.1 "GET / HTTP/1.1" 200 6137 "https://past.cent.xxxxxx.xyz/pastalist" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000132
2022-12-04T20:20:28 [INFO] - 172.19.0.1 "GET /static/water.css HTTP/1.1" 200 22669 "https://past.cent.xxxxxx.xyz/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000136
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 219615, error_len: None }', src/endpoints/create.rs:123:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-12-04T20:21:52 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000087
2022-12-04T20:23:36 [INFO] - 172.19.0.1 "GET /static/favicon.svg HTTP/1.1" 200 2095 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" 0.000086
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/endpoints/create.rs:40:41

**Comment by albocc** [comment]
Which version/Git revision did you run when you got this error?

**Comment by szabodanika** [comment]
Closing this until we get more info.
