### ISSUE TITLE
thread 'main' panicked at 'failed to spawn thread: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }'

### ISSUE THREAD

**Issue by Ofloo** [szabodanika/microbin#217]
**Describe the bug**
2023-08-28T17:23:08.966149222Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

2023-08-28T17:24:09.606143163Z 2023-08-28T17:24:09 [INFO] - MicroBin starting on http://0.0.0.0:8080

2023-08-28T17:24:09.606807104Z thread 'main' panicked at 'failed to spawn thread: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:683:29

**To Reproduce**
just paste compose.yaml too as docker-compose configuration and load .env as environment variables.

**Expected behavior**
I would expect such errors not to show and the program to function and not crash as it does.

**Screenshots**
![afbeelding](https://github.com/szabodanika/microbin/assets/2203497/d1773577-9469-4e4e-b67b-5de88f151645)

**Additional context**
Did add this variable to get more information but no such luck.
![afbeelding](https://github.com/szabodanika/microbin/assets/2203497/4212c3b8-a08d-4faf-98c5-92dc72b1e208)

**Comment by Ofloo** [comment]
Now I noticed rust_backtrace=full

once I did that got more info.

`2023-08-28T17:33:53.572737895Z    3:     0x556dcbdf5a0f - <unknown>

2023-08-28T17:33:53.572744951Z    4:     0x556dcbdf560e - <unknown>

2023-08-28T17:33:53.572798967Z    5:     0x556dcbdf6680 - <unknown>

2023-08-28T17:33:53.572805688Z    6:     0x556dcbdf6164 - <unknown>

2023-08-28T17:33:53.572828335Z    7:     0x556dcbdf60c6 - <unknown>

2023-08-28T17:33:53.572847390Z    8:     0x556dcbdf60b1 - <unknown>

2023-08-28T17:33:53.572934721Z    9:     0x556dcba03f42 - <unknown>

2023-08-28T17:33:53.572942045Z   10:     0x556dcba042d2 - <unknown>

2023-08-28T17:33:53.572961411Z   11:     0x556dcbc46f29 - <unknown>

2023-08-28T17:33:53.573005948Z   12:     0x556dcbc37435 - <unknown>

2023-08-28T17:33:53.573024408Z   13:     0x556dcbc30743 - <unknown>

2023-08-28T17:33:53.573041555Z   14:     0x556dcbc3524b - <unknown>

2023-08-28T17:33:53.573391857Z   15:     0x7f9bc750c18a - <unknown>

2023-08-28T17:33:53.573398558Z   16:     0x7f9bc750c245 - __libc_start_main

2023-08-28T17:33:53.573440483Z   17:     0x556dcba1c8fa - <unknown>

2023-08-28T17:33:53.573489366Z   18:                0x0 - <unknown>`

**Comment by pilasguru** [comment]
Same problem here:

```
microbin-microbin-1  | 2023-10-20T19:09:56 [INFO] - MicroBin starting on http://0.0.0.0:8080
microbin-microbin-1  | thread 'main' panicked at 'failed to spawn thread: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:683:29
microbin-microbin-1  | stack backtrace:
microbin-microbin-1  |    0:     0x55ef8e4c41ae - <unknown>
microbin-microbin-1  |    1:     0x55ef8e1fa6ff - <unknown>
microbin-microbin-1  |    2:     0x55ef8e49cc84 - <unknown>
microbin-microbin-1  |    3:     0x55ef8e4c5a0f - <unknown>
microbin-microbin-1  |    4:     0x55ef8e4c560e - <unknown>
microbin-microbin-1  |    5:     0x55ef8e4c6680 - <unknown>
microbin-microbin-1  |    6:     0x55ef8e4c6164 - <unknown>
microbin-microbin-1  |    7:     0x55ef8e4c60c6 - <unknown>
microbin-microbin-1  |    8:     0x55ef8e4c60b1 - <unknown>
microbin-microbin-1  |    9:     0x55ef8e0d3f42 - <unknown>
microbin-microbin-1  |   10:     0x55ef8e0d42d2 - <unknown>
microbin-microbin-1  |   11:     0x55ef8e316f29 - <unknown>
microbin-microbin-1  |   12:     0x55ef8e307435 - <unknown>
microbin-microbin-1  |   13:     0x55ef8e300743 - <unknown>
microbin-microbin-1  |   14:     0x55ef8e30524b - <unknown>
microbin-microbin-1  |   15:     0x7f6dd41f218a - <unknown>
microbin-microbin-1  |   16:     0x7f6dd41f2245 - __libc_start_main
microbin-microbin-1  |   17:     0x55ef8e0ec8fa - <unknown>
microbin-microbin-1  |   18:                0x0 - <unknown>
```

**Comment by Ofloo** [comment]
upgraded docker to docker-ce and then it worked.

**Comment by pilasguru** [comment]
Thank you @Ofloo ...  the update of docker-ce has solved the issue to me.
