### ISSUE TITLE
Crash on create,  no HTTP response

### ISSUE THREAD

**Issue by ForestJohnson** [szabodanika/microbin#241]
**Describe the bug**
When we try to POST  a paste, we get no HTTP response from server :( 

**To Reproduce**

try to post paste at https://paste.cyberia.club/

**Expected behavior**
HTTP error response and meaningful error log message printed

**Screenshots**

```
thread 'actix-rt|system:0|arbiter:0' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', src/endpoints/create.rs:77:41
```

![image](https://github.com/szabodanika/microbin/assets/7119703/c921c8c1-36d9-434d-9d55-5638eb544316)

its panicking on this line: https://github.com/szabodanika/microbin/blob/master/src/endpoints/create.rs#L77

**Comment by ForestJohnson** [comment]
please wait.......

![image](https://github.com/szabodanika/microbin/assets/7119703/a3f844e9-0318-4e24-ad63-c182722c0547)

**Comment by ForestJohnson** [comment]
Here is my chat log from how i figured out how to workaround this bug: 

https://picopublish.sequentialread.com/files/matrix_export_microbin_debug/

The jist is, deleting the previous database json file seemed to fix it: 

```
mv /var/lib/docker/volumes/microbin_microbin-data/_data/database.json /var/lib/docker/volumes/microbin_microbin-data/_data/database_backup.json
```

and then restarting microbin.


I don't want to post the database.json publicly but  I will say I did do some basic analysis on it using jq and it looks legit afaik:

```
root@paimon:/etc/docker-compose/microbin# cat /var/lib/docker/volumes/microbin_microbin-data/_data/database.json | jq keys
[
  0
]
root@paimon:/etc/docker-compose/microbin# cat /var/lib/docker/volumes/microbin_microbin-data/_data/database_backup.json | jq keys
[
  0,
  1,
  2,
  3,
  4
]
root@paimon:/etc/docker-compose/microbin# cat /var/lib/docker/volumes/microbin_microbin-data/_data/database.json | jq '.[0] | keys'
[
  "burn_after_reads",
  "content",
  "created",
  "editable",
  "encrypt_client",
  "encrypt_server",
  "encrypted_key",
  "expiration",
  "extension",
  "file",
  "id",
  "last_read",
  "pasta_type",
  "private",
  "read_count",
  "readonly"
]
root@paimon:/etc/docker-compose/microbin# cat /var/lib/docker/volumes/microbin_microbin-data/_data/database_backup.json | jq '.[0] | keys'
[
  "burn_after_reads",
  "content",
  "created",
  "editable",
  "encrypt_client",
  "encrypt_server",
  "encrypted_key",
  "expiration",
  "extension",
  "file",
  "id",
  "last_read",
  "pasta_type",
  "private",
  "read_count",
  "readonly"
]
root@paimon:/etc/docker-compose/microbin# ls -lah /var/lib/docker/volumes/microbin_microbin-data/_data/
total 56K
drwxr-xr-x 3 root root 4.0K Nov 22 21:17 .
drwx-----x 3 root root 4.0K Jan  5  2023 ..
-rw-r--r-- 1 root root  307 Nov 22 21:18 database.json
-rw-r--r-- 1 root root  37K Nov 20 18:17 database_backup.json

```

**Comment by ForestJohnson** [comment]
@szabodanika  if you would like I would be willing to share database_backup.json with you privately so you can reproduce the issue, just let me know :+1:  thanks for making this nice software :)

**Comment by ForestJohnson** [comment]
Just a thought, maybe the app should try to load the DB when it starts up, and if it can't, then it should fail to start and print a helpful error message.

**Comment by verymilan** [comment]
+1 for that issue, happened here after a few months as well. a restart appears to be a temp workaround.

**Comment by milden6** [comment]
@szabodanika 
> Is this still an issue? Any more leads?

microbin stopped working, I get an error when creating
version 2.1.0

logs:
```
thread 'actix-rt|system:0|arbiter:0' panicked at 'Failed to insert pasta.: SqliteFailure(Error { code: ReadOnly, extended_code: 8 }, Some("attempt to write a readonly database"))', src/util/db_sqlite.rs:238:6
```

response

<img width="352" height="130" alt="Image" src="https://github.com/user-attachments/assets/14883152-542a-45d6-bd31-980781b81516" />

**Comment by 3213-cmd** [comment]
+1 happened to me after 2 days of running
